#!/usr/bin/env ruby
# UNIXgod's refactoring of cpu82 FreeBSD rss parser
# depends on term/ansicolor gem... 
# might be easier to localize that at toplevel of script.
require 'rss/1.0'
require 'rss/2.0'
require 'open-uri'
require 'term/ansicolor'
include Term::ANSIColor

source = "http://www.freebsd.org/news/rss.xml"
content= String.new
open(source) { |s| content = s.read }
rss = RSS::Parser.parse(content,false)

#THEMES:
r=reset; b=bold; u=underscore
n=negative; nb=n+b
ybu=yellow+b+u; rbu=red+b+u; blb=blue+b; gb=green+b

puts <<-EOF
#{nb} RSS title:  #{rss.channel.title} #{r}
#{nb} RSS link:  #{rss.channel.link} #{r} 
#{nb} RSS description:  #{rss.channel.description} #{r} 
#{nb} RSS publication date: #{rss.channel.date} #{r} 
#{nb} Number of RSS items: #{rss.items.size} #{r}

#{ybu} Item values #{r} 
EOF

rss.items.each do |i|
  printf <<-EOF
  #{rbu} title: #{i.title} #{r}
  #{blb} link:  #{i.link} #{r}
  #{gb} description:  #{i.description} #{r}
  EOF
end
